config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfol.urls'), name='portfol')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT) 

portfol/urls.py
from django.urls import path
from .views import listview, detailview, post_share,category_list

app_name = 'article'

urlpatterns = [
    path('', listview, name='list'),
    path('tag/<slug:tag_slug>/',listview, name='post_list_by_tag'),
    path('<int:id>/share/', post_share, name='share'),
    path('<int:id>/', detailview, name='detail'),
    path('category/<int:id>/', category_list, name='category_list'),
]

portfol/models.py
from django.db import models
from django.urls import reverse

from taggit.managers import TaggableManager

# Create your models here.

STATUS = (
    ('active',"Active"),
    ('deactive', "Deactive"),
)


class Category(models.Model):
    name = models.CharField(max_length=50)

    status = models.CharField(max_length=20, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class  Meta:
        verbose_name = 'Kategoriya'
        verbose_name_plural = 'Kategoriyalar'
        ordering = ('-created_at','status')

    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse('article:category_list', args=[self.id,])



class Site(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='post_category', verbose_name="Kategoriya")
    title = models.CharField(max_length=120, verbose_name="info")
    subtitle = models.CharField(max_length=250, verbose_name="Kichik info")
    body = models.TextField(verbose_name="opisaniyasi")
    video = models.FileField(upload_to='post_videos/%Y/%m/%d/', blank=True, null=True, verbose_name="video")
    photo = models.ImageField(upload_to='post_photo/%Y/%m/%d/', blank=True, null=True, verbose_name="photo")
    see = models.PositiveIntegerField(default=100000, verbose_name="👀")

    status = models.CharField(max_length=20, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Sayt"
        verbose_name_plural = "Saytlar"
        ordering = ('-created_at',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:detail', args=[self.id,])


    
class Comment(models.Model):
    site = models.ForeignKey(Site, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=30)
    body = models.TextField(max_length=1000)

    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS)

    class Meta:
        verbose_name = "Izoh"
        verbose_name_plural = "Izohlar"
        ordering = ("-created_at",)

    def __str__(self):
        text = f"{self.name}  - {self.email}"
        return text

portfol/forms.py
from django import forms
from .models import Comment

class ShareForm(forms.Form):
    name  = forms.CharField(max_length=50)
    email = forms.EmailField()
    to  = forms.EmailField()
    comment = forms.CharField(max_length=250, required=False)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

portfol/views.py
# from django.shortcuts import render
# from .models import Site, Comment, Category 
# from .serilazers import SiteSerializer, CommentSerializer, CategorySerializer, SiteApiSerializer, CommentApiSerializer, CategoryApiSerializer

# from rest_framework.response import Response
# from rest_framework import viewsets, serializers
# from rest_framework.permissions import AllowAny, IsAuthenticated
# from rest_framework.generics import RetrieveAPIView, ListAPIView


# class CategoryViewset(viewsets.ModelViewSet):
#     queryset = Category.objects.filter(status=True)
#     serializer_class = CategorySerializer
#     permission_classes = [AllowAny]


# class SiteViewset(viewsets.ModelViewSet):
#     queryset = Site.objects.filter(status=True)
#     serializer_class = SiteSerializer
#     permission_classes = [AllowAny]


# class CommentViewset(viewsets.ModelViewSet):
#     queryset = Comment.objects.filter(status=True)
#     serializer_class = CommentSerializer
#     permission_classes = [AllowAny]


# class SiteApiDetailview(RetrieveAPIView):
#     queryset = Site.objects.filter(status=True)
#     serializer_class = SiteApiSerializer
#     permission_classes = [AllowAny]
#     lookup_field = 'slug'


# class CategoryApiDetailview(RetrieveAPIView):
#     queryset = Category.objects.filter(status=True)
#     serializer_class = CategoryApiSerializer
#     permission_classes = [AllowAny]
#     lookup_field = 'slug'


# class CommentApiDetailview(RetrieveAPIView):
#     queryset = Comment.objects.filter(status=True)
#     serializer_class = CommentApiSerializer
#     permission_classes = [AllowAny]
#     lookup_field = 'slug'







from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from portfol.models import Category, Site, Comment
from .forms import ShareForm, CommentForm

from taggit.models import Tag

# Create your views here.


def listview(request, tag_slug=None):
    most_new = Site.objects.filter(status='active').first()
    last_news = Site.objects.filter(status='active')[1:7]
    sites = Site.objects.filter(status='active')
    videos = Site.objects.exclude(video__exact='').filter(status='active')[:6]

    categories = Category.objects.filter(status='active')

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        sites = sites.filter(tags__in=[tag])


    paginator = Paginator(sites, 9)
    page = request.GET.get('page')
    try:
        sites = paginator.page(page)
    except PageNotAnInteger:
        sites = paginator.page(1)
    except EmptyPage:
        sites = paginator.page(paginator.num_pages)

    context = {
        'most_new': most_new,
        'last_news': last_news,
        'saytlar': sites,
        'categories': categories,
        'videos': videos,
        'page': page,
        'tag': tag,
    }

    return render(request, 'portfol/list.html', context)


def detailview(request, id):
    site = get_object_or_404(Site, id=id)
    sites = Site.objects.filter(category=site.category, status='active')[:4]
    categories = Category.objects.filter(status='active')

    comments = site.comments.filter(status=True)

    new_comment = None
    if request.method == 'SITE':
        comment_form = CommentForm(data=request.SITE)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.site = site
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = {
        'sayt': site,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'sites': sites,
        'categories': categories,
    }

    return render(request, 'portfol/detail.html', context)


def post_share(request, id):
    site = get_object_or_404(Site, id=id)
    categories = Category.objects.filter(status='active')
    sent = False
    print("111111111111111")
    if request.method == 'SITE':
        form = ShareForm(request.SITE)
        print("111111111111111")
        if form.is_valid():
            print("111111111111111")
            cd = form.cleaned_data

            site_url = request.build_absolute_uri(site.get_absolute_url())
            email = cd['email']
            subject = f"{cd['name']}({cd['email']}) sizga {site.title} tafsiya qildi"
            message = f"{site.title} ni quidagi link orqali o'qing: {site_url}  Comment: {cd['comment']}"
            send_mail(subject, message, email, [cd['to']])
            sent = True
            print("111111111111111")
    else:
        form = ShareForm()

    context = {'site': site, 'form': form,
               'sent': sent, 'categories': categories}

    return render(request, 'portfol/share.html', context)


def base_view(request, *args, **kwargs):
    categories = Category.objects.filter(status='active')

    context = {
        'categories': categories,
    }

    return render(request, 'base.html', context)


def category_list(request, id):
    category_object = get_object_or_404(Category, id=id)
    sites = Site.objects.filter(
        status='active', category=category_object.id)[:12]

    categories = Category.objects.filter(status='active')

    paginator = Paginator(sites, 1)
    page = request.GET.get('page')
    try:
        sites = paginator.page(page)
    except PageNotAnInteger:
        sites = paginator.page(1)
    except EmptyPage:
        sites = paginator.page(paginator.num_pages)

    context = {
        'category_object': category_object,
        'sites': sites,
        'categories': categories
    }

    return render(request, 'portfol/category_list.html', context)

templates/portfol/caegory_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>
    <section class="lower-part">
        <div class="maqolalar-news">
            <a class="aylana-label" href="#"><span>{{ category_object }} kategoriyasiga doir maqolalar</span></a>
            <div class="maqolalar-container">
                {% for site in sites %}
                <a href="{{ site.get_absolute_url }}">
                    <img src="{{ site.photo.url }}" alt="">
                    <div class="maqolalar-container__content">
                        <h5>{{ site.title }}</h5>
                        <p>{{ site.body|slice:"350" }}</p>
                    </div>
                </a>
                {% endfor %}
            </div>
            <div class="paginator">
                {% include "paginator.html" with page=sites %}
            </div>
        </div>
    </section>
</main>
{% endblock content %}

templates/portfol/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>
    <section class="lower-part">
        <div class="saytlar-news">
            <a class="aylana-label" href="#"><span>{{ category_object }} kategoriyasiga doir saytlar</span></a>
            <div class="saytlar-container">
                {% for site in sites %}
                <a href="{{ site.get_absolute_url }}">
                    <img src="{{ site.photo.url }}" alt="">
                    <div class="saytlar">
                        <h5>{{ site.title }}</h5>
                        <p>{{ site.body|slice:"350" }}</p>
                    </div>
                </a>
                {% endfor %}
            </div>
            <div class="paginator">
                {% include "paginator.html" with page=sites %}
            </div>
        </div>
    </section>
</main>
{% endblock content %}

templates/portfol/detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/artice.css' %}">
<main>
    <section class="top-news">
        {% most_comments %}
        <div class="portfol-layout">
            <div class="portfol-layout__header">
                <div class="header-time"><span class="time-ui">{{ sayt.created_at|date:"d/m/Y | f"}}</span></div>
                <div class="content-views"><span class="">{{ sayt.see }}</span></div>
                <div class="share-news">

                </div>
            </div>
            <div class="portfol-layout__content">
                <h1>{{ sayt.title }}</h1>
                <h4>{{ sayt.subtitle }}</h4>
                <div class="content-img">
                    <img src="{{ sayt.photo.url }}" alt="">
                    <div class="main-img__caption">{{ sayt.photo }}</div>
                </div>
                <p dir="auto">{{ sayt.body }}</p>
                <div class="article-layout__bottom">
                    <ul>
                        {% for tag in sayt.tags.all %}
                        <li class="bottom-tag"><a href="{% url 'portfol:site_list_by_tag' tag.slug %}">#{{ tag.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="article-layout__comment">
                <div class="comment-head"><span>4 comments</span>test</div>
                <div class="comment-form">
                    <div class="comment-avatar">J</div>

                    <form method='site' id="comment-form" onsubmit="myFunction(e)">
                        {% csrf_token %}
                        <input required id="id_name" type="text" name="name" placeholder="name" autocomplete="username">

                        <input required id="id_email" type="text" name="email" placeholder="email"
                            autocomplete="username">

                        <textarea name="body" id="id_body" rows="2" placeholder="comment"></textarea>

                        <input type="submit" value="send">
                    </form>

                </div>
                <div class="comments-body">
                    <!-- <div class="comment-ordering">
                            <label class="ordering__new">
                                <input type="radio" checked="checked" name="radio" onclick="console.log(this)">
                                <span>NEW</span>
                                <span class="ordering__checkmark"></span>
                            </label>
                            <label class="ordering__older">
                                <input type="radio" name="radio">
                                <span>OLDER</span>
                                <span class="ordering__checkmark"></span>
                            </label>
                        </div> -->
                    <div class="comments-list">
                        {% for comment in comments %}
                        <div class="comment-container" itemid="1">
                            <div class="comment-avatar">{{ comment.name|slice:"1" }}</div>
                            <div class="comment-info">
                                <div class="comment-info-head">
                                    <p class="comment-username">{{ comment.name }}</p>
                                    <p class="comment-time time-ui">{{ comment.created_at|date:"d/m/Y | f" }}</p>
                                </div>
                                <p class="comment-context">{{ comment.body }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>
        <script>
            function myFunction(e) {
                e.preventDefault();
            }
        </script>
        <div class="portfol__right">
            {% lastest_postes %}
            {% most_view %}
        </div>
    </section>
    <section class="bottom-news">
        <div class="tag-news">
            <div class="tags-news__head">
            </div>
            <div class="tags-news__grid">
                {% for site in sites %}
                <a href="{{ site.get_absolute_url }}">
                    <img src="{{ site.photo.url }}" alt="">
                    <div class="tags-news__content">
                        <div><span class="time-ui">{{ site.created_at|date:"d/m/Y | f" }}</span></div>
                        <p>{{ site.title }}</p>
                    </div>
                </a>
                {% endfor %}

            </div>
        </div>
        <div class="site-news">
            <div class="site-news__head">
                <a class="aylana-label" href="#"><span>Saytlarim</span></a>
            </div>
            <div class="site-carousel">
                <div class="carousel" data-flickity='{ "groupCells": 4 }'>

                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/1 (1).png' %}" alt="" srcset="">
                            </div>
                            <div class="carousel-content">
                                Above, you see the codes from inside i mean from visual studio code
                            </div>
                        </a>
                    </div>
                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/1 (2).png' %}" alt="" srcset="">
                            </div>
                            <div class="carousel-content">
                                Here i gathered all codes from each file in my own sites
                            </div>
                        </a>
                    </div>
                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/1 (3).png' %}" alt="" srcset="">
                            </div>
                            <div class="carousel-content">
                                I cannot understand why do we need to write informations about photos above
                            </div>
                        </a>
                    </div>
                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/1 (4).png' %}" alt="" srcset="">
                            </div>
                            <div class="carousel-content">
                                I wanna say only one thing while you reading this i'm loughing you know why, because you spent your time useless
                            </div>
                        </a>
                    </div>
                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/1 (5).png' %}" alt="" srcset="">
                            </div>
                            <div class="carousel-content">
                                I cannot understand why do we need to write informations about photos above
                            </div>
                        </a>
                    </div>
                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/1 (6).png' %}" alt=""
                                    srcset="">
                            </div>
                            <div class="carousel-content">
                                Above, you see the codes from inside i mean from visual studio code
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock content %}

templates/portfol/list.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load static %}

{% block content %}
<main>
    <section class="top-news">
        <div class="top-news__center">
            <a class="center-news__big" href="{{ most_new.get_absolute_url }}">
                <img class="big-news__img" src="{{ most_new.photo.url }}" alt="">
                <div class="big-news__content">
                    <div><span class="time-ui">{{ most_new.created_at|date:"d/m/Y | f" }}</span></div>
                    <p>{{ most_new.title }}</p>
                    <p>{{ most_new.subtitle }}</p>
                </div>
            </a>

            <div class="center-news__grid">
                {% for sayt in last_news %}
                <a href="{{ sayt.get_absolute_url }}">
                    {% if satr.photo %}
                    <img src="{{ sayt.photo.url }}" alt="">
                    {% endif %}
                    <div class="center-news__grid-content">
                        <div><span class="time-ui">{{ sayt.created_at|date:"d/m/Y | f" }}</span></div>
                        <p>{{ sayt.title }}</p>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
        {% most_comments %}
    </section>
    <section class="lower-part">
        <div class="saytlar-news">
            <a class="aylana-label" href="#"><span>Saytlar</span></a>
            <div class="saytlar-container">
                {% for sayt in saytlar %}
                <a href="{{ sayt.get_absolute_url }}">
                    <img src="{{ sayt.photo.url }}" alt="">
                    <div class="saytlar-container__content">
                        <h5>{{ sayt.title }}</h5>
                        <p>{{ sayt.body| slice:"350" }}</p>
                    </div>
                </a>
                {% endfor %}
            </div>
            <div class="paginator">
                {% include "paginator.html" with page=saytlar %}
            </div>
        </div>
        <div class="saytlar-news">
            <div class="saytlar-news__head">
                <a class="aylana-label" href="#"><span>Saytlarim</span></a>
            </div>
            <div class="saytlar-carousel">
                <div class="carousel" data-flickity='{ "groupCells": 4 }'>

                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/1.png' %}" alt="" srcset="">
                            </div>
                            <div class="carousel-content">
                                Mening saytlarimning qanday qilib ishlashi
                            </div>
                        </a>
                    </div>
                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/2.png' %}" alt="" srcset="">
                            </div>
                            <div class="carousel-content">
                                Here's shown you can control with my some sites in my portfolio
                            </div>
                        </a>
                    </div>
                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/3.png' %}" alt="" srcset="">
                            </div>
                            <div class="carousel-content">
                                How i create by using API not front-end part, and this means i know my job as good as needed
                            </div>
                        </a>
                    </div>
                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/4.png' %}" alt="" srcset="">
                            </div>
                            <div class="carousel-content">
                                My another site where i used API, but i wanted to use front-end and remembered that i'm back-ender ahahahah
                            </div>
                        </a>
                    </div>
                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/3.png' %}" alt="" srcset="">
                            </div>
                            <div class="carousel-content">
                                Here's shown you can control with my some sites in my portfolio
                            </div>
                        </a>
                    </div>
                    <div class="carousel-cell">
                        <a href="">
                            <div class="carousel-img">
                                <img src="{% static 'images/1.png' %}" alt=""
                                    srcset="">
                            </div>
                            <div class="carousel-content">
                                My another site where i used API, but i wanted to use front-end and remembered that i'm back-ender ahahahah
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="media-news">
            <div class="media-container">
                {% for site in videos %}
                <a href="{{ site.get_absolute_url }}">
                    <div class="media-img"><img src="{{ site.photo.url }}" alt=""></div>
                    <div class="media-container__content">
                        <div><span class="time-ui">{{ site.created_at|date:"d/m/Y | f" }}</span></div>
                        <p>{{ site.title }}</p>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
    </section>
</main>
{% endblock content %}

templates/portfol/share.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'css/share.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&display=swap" rel="stylesheet">
</head>


<div class="content-container">
    <div>
        <h2>{{ site.title }}</h2>
        <p>{{ site.subtitle }}</p>
    </div>
    <div class="form-container">
        <form method="site">
            {% csrf_token %}
            <div class="row">
                <div class="col-25">
                    <label for="id_name">Ismingiz</label>
                </div>
                <div class="col-75">
                    <input type="text" required id="id_name" name="id_name" placeholder="Ism..">
                </div>
            </div>

            <div class="row">
                <div class="col-25">
                    <label for="id_email">E-mail</label>
                </div>
                <div class="col-75">
                    <input type="email" required id="id_email" name="id_email" placeholder="Your e-mail..">
                </div>
            </div>

            <div class="row">
                <div class="col-25">
                    <label for="id_to">Friend e-mail</label>
                </div>
                <div class="col-75">
                    <input type="email" required id="id_to" name="id_to" placeholder="Friend e-mail..">
                </div>
            </div>

            <div class="row">
                <div class="col-25">
                    <label for="id_comment">saytimga izoh</label>
                </div>
                <div class="col-75">
                    <textarea id="id_comment" required name="id_comment" placeholder="Yozing.."
                        style="height:200px"></textarea>
                </div>
            </div>
            <div class="row">
                <input type="submit" required value="Send">
            </div>
        </form>
    </div>
</div>

{% endblock content %}